CREATE TABLE IF NOT EXISTS players (
  id INTEGER PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  coins DECIMAL(24,10) NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT (datetime('now','localtime'))
);